services:
  db:
    image: 'mysql:8.0'
    restart: always
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: mysql_db
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: sergei
      MYSQL_PASSWORD: secret
  minio:
    image: 'minio/minio'
    ports:
      - "9001:9001"
      - "9000:9000"
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    environment:
      - MINIO_ROOT_USER=username
      - MINIO_ROOT_PASSWORD=password
      - MINIO_DEFAULT_BUCKETS=your_bucket_name
    restart: always
    depends_on:
      - db
  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    command: redis-server
    volumes:
      - ~/data/redis:/var/lib/redis
      - ~/data/redis/config:/usr/local/etc/redis/redis.conf
volumes:
  mysql_data:
  minio_data:
